[workspace]
resolver = "3"
members = ["gbrs", "gbrs_frontend", "gbrs_retro"]

[workspace.package]
edition = "2024"
description = "A Gameboy emulator"
readme = "README.md"
homepage = "https://github.com/abusch/gb-rs"
repository = "https://github.com/abusch/gb-rs"
license = "MIT OR Apache-2.0"
keywords = ["emulator", "gameboy"]

[workspace.dependencies]
ansi_term = "0.12"
anyhow = "1.0"
bitflags = "2.8"
bitvec = "1.0"
byteorder = "1.4"
clap = { version = "4.0", features = ["derive"] }
cpal = "0.18"
env_logger = "0.11"
libretro = { package = "libretro-core", version = "1" }
log = { version = "0.4", features = ["release_max_level_info"] }
pixels = "0.17.1"
png = "0.18"
ringbuf = "0.5"
rustyline = "18"
winit = "0.30"
zip = "8.6.0"

gbrs = { path = "gbrs/", version = "0.2.0" }

[profile.release]
debug = true
incremental = true
