[package]
name = "gb-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
bitvec = "1.0.0"
ctrlc = "3.2.1"
log = "0.4.14"
env_logger = "0.9.0"
