[package]
name = "gb-rs"
version = "0.1.0"
edition = "2021"
authors = ["Antoine Büsch <antoine.busch@gmail.com>"]
description = "A Gameboy emulator"
repository = "https://github.com/abusch/gb-rs"
homepage = "https://github.com/abusch/gb-rs"
keywords = ["emulator", "gameboy"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
bitflags = "1.3"
bitvec = "1.0"
byteorder = "1.4"
clap = { version = "4.0", features = ["derive"]}
cpal = "0.14"
log = "0.4"
env_logger = "0.10"
pixels = "0.11.0"
png = "0.17"
ringbuf = "0.3"
rustyline = "10"
winit = "0.27"
winit_input_helper = "0.13"

[profile.release]
debug = true
incremental = true
